### ISSUE TITLE
[question] example for multiple carousel on one html page?

### ISSUE THREAD

**Issue by CharlesKumar** [SebasWebDev/sebastian-carousel#1]

**Comment by SebasWebDev** [comment]
The [index.html](https://github.com/SebasWebDev/sebastian-carousel/blob/master/index.html) has multiple carousels.
Every element with the attribute `data-sc` is a different instance of the plugin, so you can have as many as you need.

**Comment by SebasWebDev** [comment]
Closing the issue as I believe it has been clarified. @CharlesKumar Let me know if you still have questions.
